name=bava
version=1.0.2
author=Nishanth Raj
maintainer=Nishanth Raj <jpnishanthraj@gmail.com>
sentence=O(1) zero-allocation hardware variable teleportation.
paragraph=A deterministic, ultra-low latency (64us) serial protocol for cross-platform MCU communication.
category=Communication
url=https://github.com/NishanthRaj707/bavaprotocol
architectures=*